project:
  type: book
  output-dir: docs

book:
  title: "Selamat Datang di II-2100 Komunikasi Inter Personal dan Publik"
  author: "Armein Z. R. Langi"
  date: "9/2/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - asesmen.qmd
    - kuliah/K-1.qmd
    - kuliah/K-2.qmd
    - kuliah/K-3.qmd
    - kuliah/K-4.qmd
    - kuliah/K-5.qmd
    - kuliah/K-6.qmd
    - kuliah/K-7.qmd
    - kuliah/K-8.qmd
    - kuliah/K-9.qmd
    - kuliah/K-10.qmd
    - kuliah/K-11.qmd
    - kuliah/K-12.qmd
    - kuliah/K-13.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  latex:
    documentclass: scrreprt
    


execute:
  echo: false
jupyter: python3

